### ISSUE TITLE
still showing RPC event not playing

### ISSUE THREAD

**Issue by Frankity** [TheTimebike/SIVA#1]
hi, i'm facing this issue, i stopped playing destiny like for 15 mins but the app keep sending rich presence even without the game running:

![image](https://user-images.githubusercontent.com/1179431/60897417-abbc8e80-a22d-11e9-952c-17fe8fc69554.png)

**Comment by TheTimebike** [comment]
I have been trying to find a way where I can use the Bungie API to see if a user is online or offline, unfortunately not to much luck. Until I can find a workaround for this, click the "Stop!" button and the RPC event will stop.

**Comment by Frankity** [comment]
sorry for reopen, i think you can check if the game process is running or not to stop sending rpc and update button status.

**Comment by TheTimebike** [comment]
This would mean that it would not work for console users, and for users who run the app on a separate PC from which they game.

**Comment by Frankity** [comment]
What if you validate the platform to enable that feature?, i mean as you always ask for which platform, validate process if Battle.net.
