### ISSUE TITLE
Failed to execute script SIVA

### ISSUE THREAD

**Issue by adelwolf** [TheTimebike/SIVA#2]
Get a "Failed to execute script SIVA" error. Any advice?

**Comment by TheTimebike** [comment]
What version of SIVA are you using? Have you ran SIVA before and is there a "siva_files" folder next to the program?

**Comment by adelwolf** [comment]
Newest version. Havent ran before, and no folder. Going to run an older version and upgrade from there and see if that works.

**Comment by adelwolf** [comment]
Upgrading works.

**Comment by TheTimebike** [comment]
You are now able to run SIVA?

**Comment by TheTimebike** [comment]
Bug found and fixed in version 0.4.0. For anyone who is currently experiencing this, downgrade to an older version and upgrade from that.
