### ISSUE TITLE
Username when using Steam Option

### ISSUE THREAD

**Issue by SgtBreadStick** [TheTimebike/SIVA#3]
Hello,
When it comes to "username", what do I put in when I'm using Steam mode?

Can't seem to get SIVA working because of it.

**Comment by TheTimebike** [comment]
Yes, this is an issue being worked on. The problem is that steam names are not unique. meaning I have to add a system to allow steam users to select their account from a list, which is taking longer than I had expected. Sorry for the downtime.

**Comment by TheTimebike** [comment]
Update v1.1.0 has been released which features support for accounts which share a username. Any bugs in update v1.1.0 should have their own issue created.
