### ISSUE TITLE
Same username when using the Steam platform

### ISSUE THREAD

**Issue by WarheadTaylor** [TheTimebike/SIVA#4]
When you have the same display name as someone on Steam (for example, in my case, **Warhead**), it'll only list one user with that case.

![image](https://user-images.githubusercontent.com/4128606/67018970-d3cf4f80-f0b0-11e9-8fb4-0ea6eab6dba8.png)

My user ID doesn't show up on this list, so I'm not able to select my username.

Could we manually pass the ID if we know it?

**Comment by TheTimebike** [comment]
I'll see to updating SIVA so you can pass the ID.
https://github.com/Bungie-net/api/issues/1054
Bungie API team are aware of this issue and hopefully working on a fix.

**Comment by TheTimebike** [comment]
Release v1.2.0 comes with support for account selection with ID's. Enable this mode under the SIVA tab in the program.
