### ISSUE TITLE
Doesn't seem to support username that's other than english

### ISSUE THREAD

**Issue by teFrost** [TheTimebike/SIVA#5]
My steam username is in japanese and when I press start there's no "select account" window popping up.
I have my API key set too, platform selected to steam, there's a way to login with ID but I am not smart enough to get my ID.

**Comment by TheTimebike** [comment]
Would you be able to post your steam username so I can test it in a debugging version of SIVA? Thanks

**Comment by teFrost** [comment]
My steam username is オートミール

**Comment by TheTimebike** [comment]
I'll work on a fix for this. In the meantime, your ID is 4611686018483310528

**Comment by TheTimebike** [comment]
I'm having issues replicating this on my end, would you be able to try it again to see if the error still occurs?

**Comment by teFrost** [comment]
I just tried and it work just fine, but if I press stop and start again it won't work, and maybe its not a issue with my username.

**Comment by TheTimebike** [comment]
If that's the case its probably something on Bungies' end that's causing it. I'm going to keep this issue open in-case the issue starts again or anyone else experiences something similar.
