### ISSUE TITLE
Issue with finding Steam Username

### ISSUE THREAD

**Issue by ghost** [TheTimebike/SIVA#6]
My steam name was pretty basic and it listed a bunch of results, but none of which matched my profile ID so I tried searching by that instead and came up empty.

Would it be possible to add the ability to search by profile ID to find yourself easier?

EDIT Found a quick work around by changing my name to something else.

**Comment by TheTimebike** [comment]
There is a feature in the latest version of SIVA that allows you to select your profile through ID. Under the "SIVA" tab there is an option called "Login with ID". These ID's are unique so there is no need to have a browser for them, and the Bungie API does not provide a way to auto-fill ID's, so you have to put your entire ID in.
