### ISSUE TITLE
Can't get SIVA to show my presence

### ISSUE THREAD

**Issue by Thomasedv** [TheTimebike/SIVA#7]
Using an API key i made, tested both username for xbox and steam with ID (cross save, not really sure what it falls under), i press start and get no errors. But Discord only shows the default game presence for Destiny. Is there anything else i need to change? This is the same computer as Destiny is running on, and i can't really remove Destiny from discords game tab either. Is there anything that needs to be tweaked in the API on bungie.net?  

Running latest version.

**Comment by TheTimebike** [comment]
I think this is something on discords end. If there was an error on Bungies or SIVAs end, it would show an error message. Try running and starting SIVA while Destiny is closed and see what presence discord has.

**Comment by Thomasedv** [comment]
Running it without Destiny up works, and it works after i started Destiny. Might be that i ended up with multiple instances of SIVA running the first time, but it does work now!

~~I have one suggestion for improvement, since it can't tell if you are online or not, how about an option that makes it broadcast only as long as Destiny is running on that computer SIVA is running? (Would save PC users some hassle) Can be done either by watching a marked executable by the user, or simply see if a program called destiny2.exe is running.~~

Nevermind actually. I know a bit of python, so i implemented it myself. I did a lot of tweaks to make it work for my level of understanding though, and basically made a single watcher thread that does checking as well as updates at a target interval. 

I can add that i think you are catching an error where cross-play is involved but the error is not shown to the user. I got an error when using Steam as platform, presumably because i have Xbox Cross-Save. No error is shown but the traceback is printed by python, where the API says invalid parameters or something like that. Changing just to the number for Xbox works.

**Comment by TheTimebike** [comment]
Thanks for your explanation, I'll be looking into this to see whats going on there with cross-play. Would you be able to send me your username so I would be able to do some testing in a debug version?

**Comment by Thomasedv** [comment]
Username is Thomasedv for both Xbox/steam. I tried steam id to with the setting enabled. No error were given with both name and id, so i'm fairly sure that part works, and just the API not being able to handle cross play without the "root" save platform. 
Steam ID: 76561198072236798
